AWSTemplateFormatVersion: '2010-09-09'
Description: My first S3 bucket deployed via CloudFormation

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: rubio24-cloud-bucket-2026 